### ISSUE TITLE
Preview variables in command palette

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#10]
Currently, if a command contains a variable, the command palette shows the variable's name:

![kuva](https://user-images.githubusercontent.com/13002142/132369318-4f956e11-a39f-442f-b335-1ba304670a36.png)

A preview feature could show the variable content before the command gets executed. In this example case, the date could be shown like this:

![kuva](https://user-images.githubusercontent.com/13002142/132369599-5c7825ed-e8ab-4248-9704-650599a8699c.png)

This feature could be turned off in the settings. It will be on by default.

**Support for [aliases](https://github.com/Taitava/obsidian-shellcommands/issues/6)**: You could write variables in aliases too. They would have no practical change to how a command would be executed, but this way your alias can show all the variable values that the command is going to use. For example, the above `mkdir {{date:YYYY-MM-DD}}` command could have an alias like this: `Create today's folder {{date:YYYY-MM-DD}}`, which would show up in the command palette as `Create today's folder 2021-09-07`.

**Comment by FelipeRearden** [comment]
@Taitava !!
Great idea !This is an amazing feature! Brings this plug-in UI to a new level

**Comment by Taitava** [comment]
Released. 🙂
