### ISSUE TITLE
Bash etc: Newline characters that come from variable values disappear

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#109]
Example:
1. Copy all of the text from this issue to the clipboard, including newlines in between paragraphs.
2. Execute a shell command like `echo {{clipboard}}`, make sure the output is either a _notification balloon_, or _current file_.

On Windows PowerShell, the test works ok, the newline characters are preserved in the output. But on Bash and Zsh (latter tested by @FelipeRearden on Mac, I tested Bash on Linux), the newline characters disappear.

I think it happens because these [Bourne family shells](https://en.wikipedia.org/wiki/Bourne_shell#Other_shells) consider an escaped newline to mean something like _"continue this command in the next line"_, i.e. just ignore the newline character, pretend it never existed. This is just my guessing, and I can't say for certain that this is how these shells really think.

I need to make the escaping system to do the following:
- Convert newline characters to a literal `\n`. A shell will later convert it back to it's original meaning.
- Convert carriage return characters to a literal `\r`. A shell will later convert it back to it's original meaning.
- This will also result in converting a carriage return & newline pair to a literal `\r\n` ~~(used on Windows). While Windows PowerShell does not suffer from this bug, I think it's simpler to do this replacing for PowerShell too, as it will be more streamlined when newline replacing is the same for all shells. The escape character `\` will of course be different for PowerShell (`` ` ``), i.e. `\r\n` will actually be `` `r`n ``. [According to this source, this should work for PowerShell](https://devblogs.microsoft.com/scripting/powertip-new-lines-with-powershell/).~~ Edit: no, this would not work for PowerShell, so there will be no changes regarding PowerShell. 👍 But in case a variable happens to output a carriage return & newline pair on Mac/Linux (if file content happens to have one), this will still give a literal `\r\n`.

Edit: Actually, it seems that I need to double the escape character, so `\n` will become `\\n`. Otherwise `echo -e` on Bash will output a literal `n` instead of a newline.

**Comment by Taitava** [comment]
Fixed. I'll release a `beta4` soon.

**Comment by FelipeRearden** [comment]
AMAZING!!!!!!!!!

**Comment by Taitava** [comment]
`beta4` is now released: https://github.com/Taitava/obsidian-shellcommands/releases/tag/0.7.0-beta4

@FelipeRearden can you confirm here that newlines work now? Just one thing that I've learned about the `echo` command on Bash: I needed to add an `-e` parameter to the command, otherwise newlines appear as `\n` in the output. So a complete example command: `echo -e {{clipboard}}`, and another: `echo -e {{selection}}`.

As you have Zsh instead of Bash, I do not know if your `echo` works differently.

**Comment by FelipeRearden** [comment]
> `beta4` is now released: https://github.com/Taitava/obsidian-shellcommands/releases/tag/0.7.0-beta4

Thank you very much @Taitava !!!! :)

> @FelipeRearden can you confirm here that newlines work now? Just one thing that I've learned about the `echo` command on Bash: I needed to add an `-e` parameter to the command, otherwise newlines appear as `\n` in the output. So a complete example command: `echo -e {{clipboard}}`, and another: `echo -e {{selection}}`.

Sure @Taitava !!! I will test and get back to you. 

I have some chores and errands to do today but tomorrow morning I will concentrate in testing beta 4 :)
- Sorry for not testing beta 4 now :)

> As you have Zsh instead of Bash, I do not know if your `echo` works differently.

I'm gonna test `echo` , `echo -e` and `printf` too. Thanks for the tip :)


## Question for @Taitava  about testing beta 4

Should I test everything ({{path_}}) or focus only on {{clipboard}} and {{selection}} ?

Should I take a look at `data_backup.json` or not?


Thanks!!!!!

**Comment by Taitava** [comment]
> I have some chores and errands to do today but tomorrow morning I will concentrate in testing beta 4 :)
> 
>   * Sorry for not testing beta 4 now :)

Take your time! 🙂 I don't have any time expectations. Even if I sometimes happen to do stuff fast and post a lot, I don't expect others to react immediately 🙂. I can wait. We all have our timetables.

> 
> 
> > As you have Zsh instead of Bash, I do not know if your `echo` works differently.
> 
> I'm gonna test `echo` , `echo -e` and `printf` too. Thanks for the tip :)

Good ideas!

> ## Question for @Taitava about testing beta 4
> 
> Should I test everything ({{path_}}) or focus only on {{clipboard}} and {{selection}} ?
> 
> Should I take a look at `data_backup.json` or not?
> 
> Thanks!!!!!

If it's not too much work, you could test all your variable tests just in case, although `{{clipboard}}` and `{{selection}}` are the most important. No need to test backup files, I believe it works solidly now.

Thank you a lot! You are helping a lot! 😎

**Comment by FelipeRearden** [comment]
> Take your time! 🙂 I don't have any time expectations. Even if I sometimes happen to do stuff fast and post a lot, I don't expect others to react immediately 🙂. I can wait. We all have our timetables

Thanks @Taitava !! For SC I always want to concentrate 100% when testing because I know that we need to be very calm to don't make a mistake and prepare a good explanation if I find something that I judge as wrong ;)

> If it's not too much work, you could test all your variable tests just in case, although {{clipboard}} and {{selection}} are the most important. No need to test backup files, I believe it works solidly now.

No problem at all @Taitava !!! I go for full test tomorrow:)

Thanks we talk tomorrow!!!!!!!

**Comment by Taitava** [comment]
> > Take your time! 🙂 I don't have any time expectations. Even if I sometimes happen to do stuff fast and post a lot, I don't expect others to react immediately 🙂. I can wait. We all have our timetables
> 
> Thanks @Taitava !! For SC I always want to concentrate 100% when testing because I know that we need to be very calm to don't make a mistake and prepare a good explanation if I find something that I judge as wrong ;)

That's also true! "Postponing" something for a bit later, peaceful time, can be more _respectful_ than trying to do something quickly and in a hurry. Waiting is not always a bad thing. 🙂 

> 
> > If it's not too much work, you could test all your variable tests just in case, although {{clipboard}} and {{selection}} are the most important. No need to test backup files, I believe it works solidly now.
> 
> No problem at all @Taitava !!! I go for full test tomorrow:)
> 
> Thanks we talk tomorrow!!!!!!!

Thank you! 🌞

**Comment by FelipeRearden** [comment]
Working perfect on version `0.7.0-beta4` Obsidian `0.12.19`

More details about the test here in #96

**Comment by Taitava** [comment]
Really nice to know! 🙂
