### ISSUE TITLE
Events, part 1

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#123]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/60

Events that will be implemented now:
- [x] _When Obsidian is opened_ (more specifically, this would actually be: _when the plugin is loaded_). This would allow a user to open a set of tool applications every time they open a certain Obsidian vault, e.g. [GIMP](https://www.gimp.org/) for manipulating note related images.
- [x] _When Obsidian is closed_.
- [x] *Every n seconds* (seconds could be later changed to a decimal number, allowing executing something e.g. every 0.5 seconds if needed)
- [x] *Command palette*: Currently this is the only action that can launch shell commands. It's included in this list to mark that a user can also turn it off, if they use other launchers for a shell command. Turn off = means that a shell command would not appear in command palette.
- [x] _When a user switches the active panel_. Example: Execute a shell command that reads the current file's last modification time and outputs the information to status bar (the status bar output feature is still under planning, see #16 ). The event helps to automatically give information for the file that is currently actively viewed in Obsidian.
- [x] *Context menus*: This would allow a user to define a new item in context menus (editor context menu, file navigation context menu, what else are there?). By clicking that context menu item, a shell command is executed, with possible event related variables like to what file was the context menu related to, or to what position in the editor.

New variables:
- [x] `{{event_file_extension}}`
- [x] `{{event_file_name}}`
- [x] `{{event_file_path}}`
- [x] `{{event_folder_name}}`
- [x] `{{event_folder_path}}`
- [x] `{{event_tags}}`
- [x] `{{event_title}}`
- [x] `{{event_yaml_value}}`

Other things:
- [x] Write documentation for the new events.
- [x] Write documentation for the new variables.
- [x] Add _See also_ sections to variable documentation, will contain links to similar variables.
- [x] Write example events to documentation.
- [x] Add links to each event's documentation page in settings.
- [x] Create tests for events.

**Comment by DaveyUS** [comment]
What are the chances we could get an event that triggers when a link is clicked with a {{event_link_text}} variable?

A usage example would be when clicking [[audiofile.mp3]] the event would trigger allowing me pass the mp3 name to a python script. 

Amazing plugin btw!

**Comment by Taitava** [comment]
> What are the chances we could get an event that triggers when a link is clicked with a {{event_link_text}} variable?
> 
> A usage example would be when clicking [[audiofile.mp3]] the event would trigger allowing me pass the mp3 name to a python script.
> 

Thanks for the question! 🙂  To keep idea discussions separate from implementation issues, I answered your question in this events related discussion: https://github.com/Taitava/obsidian-shellcommands/discussions/60#discussioncomment-1907260

> Amazing plugin btw!

Thank you! 😎

**Comment by Taitava** [comment]
Released.
