### ISSUE TITLE
Output to status bar: Don't ignore empty output

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#124]
Currently, if a shell command outputs nothing, and if status bar already contains content from a previous execution, the old content stays in the status bar.

Empty output content should make the status bar content empty.

**Comment by FelipeRearden** [comment]
> Currently, if a shell command outputs nothing, and if status bar already contains content from a previous execution, the old content stays in the status bar.
> 
> 
> 
> Empty output content should make the status bar content empty.

@Taitava please take a look at this #127 before making changes in the content of the status bar 🙏 !!!!!!

Thanks !!!

**Comment by Taitava** [comment]
Ok, as we've had some discussion in #127, I think #127 will probably be so different that the change mentioned in this issue won't affect it at all, I think.

@FelipeRearden what do you think about in general for this status bar change, is it ok that empty output to status bar will clear it? Or do you see some problems here? 🙂 I can also move this from `0.9.0` to `0.10.0` so that this can be first tested in a beta version (I won't probably make a beta for `0.9.0`, but `0.10.0` will have one).

**Comment by FelipeRearden** [comment]
> Ok, as we've had some discussion in #127, I think #127 will probably be so different that the change mentioned in this issue won't affect it at all, I think.

100% agree!

> @FelipeRearden what do you think about in general for this status bar change, is it ok that empty output to status bar will clear it? Or do you see some problems here? 🙂 I can also move this from `0.9.0` to `0.10.0` so that this can be first tested in a beta version (I won't probably make a beta for `0.9.0`, but `0.10.0` will have one).

I don't see any problem @Taitava ! My only concern was about my FR on #127. I was afraid that you made a change today that could make you rewrite/redo in the future due to #127. But it's all clear now and I don't see ant issue about clear the status bar :)

**Comment by Taitava** [comment]
Done. 🙂

**Comment by Taitava** [comment]
Released.
