### ISSUE TITLE
Ability to hide shell commands from the command palette

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#125]
#123 will bring new ways how shell commands can be executed, and discussion #60 mentions an idea to be able to exclude shell commands from Obsidian's command palette:

From https://github.com/Taitava/obsidian-shellcommands/discussions/60#discussion-3602335 :
> - *Command palette*: Currently this is the only action that can launch shell commands. It's included in this list to mark that a user can also turn it off, if they use other launchers for a shell command. Turn off = means that a shell command would not appear in command palette.

There will be three options for a shell command's availability in the command palette:
- Command palette & hotkeys
- Hotkeys only (not shown in command palette, but can be executed via hotkeys. Clean up your command palette by hiding stuff that you always execute via hotkeys anyway!)
- Excluded (not shown in command palette, and no ability to assign hotkeys. Good for fully automated shell commands that you never need to execute manually)

**Comment by FelipeRearden** [comment]
Fantastic idea @Taitava !!!!!!

Didn't know that was possible to manage items from the command palette :)

**Comment by Taitava** [comment]
Released.
