### ISSUE TITLE
Variable name doesn't work with Sync ?

### ISSUE THREAD

**Issue by Mara-Li** [Taitava/obsidian-shellcommands#136]
Variable doesn't work : 
- Variable prevent to open the command in modal
- Variable seems to break the last character when adding the last `}}` 
![image](https://user-images.githubusercontent.com/30244939/151222239-92ed76c2-909c-4d64-a053-00f87d657383.png)
![image](https://user-images.githubusercontent.com/30244939/151222345-96d6c595-3baa-4191-a031-991c80a3c6b9.png)
![image](https://user-images.githubusercontent.com/30244939/151222502-d023d0e5-9c89-4230-9f40-d71f84a12b7f.png)

**Comment by Mara-Li** [comment]
I try a lot around the plugin, and it seems to break sync. 

It worked well before, but now I can't really make it work. It works without problem on a test vault.

**Comment by Taitava** [comment]
Thanks for your report! I opened [a discussion for this](https://github.com/Taitava/obsidian-shellcommands/discussions/137). So let's first discuss the problem there, and when we find a fix for this, I'll update it to this issue and fix the code. This is just to keep issues short, and have longer stuff in discussions. 🙂

**Comment by Taitava** [comment]
Updating _Dynamic highlights_ to version `0.2.2` solves this issue. However, there's also something to be fixed in SC's side too (to prevent similar issues happening in the future), for which I created a new issue #152.
