### ISSUE TITLE
Hotkeys for output channel: Ask after execution

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#145]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/138

I decided to do these improvements later, not in `0.10.0`.

- [x] Add hotkeys `Ctrl`/`Cmd` + ~~`1`, `2`, `3` etc...~~ **a letter** to use different output channel buttons. Read more: https://github.com/Taitava/obsidian-shellcommands/discussions/139
- [x] Add a `Shift` modifier to the abovementioned ~~number~~ **letter** hotkeys to close the modal after using an output channel.
- [x] Make `Ctrl`/`Cmd` + clicking the buttons also close the modal.
- [x] Change the hotkeys from numbers to letters: https://github.com/Taitava/obsidian-shellcommands/discussions/139#discussioncomment-2302643
- [x] Change the tooltip: https://github.com/Taitava/obsidian-shellcommands/discussions/139#discussioncomment-2301211

**Comment by Taitava** [comment]
@FelipeRearden I'll need your help testing this when a beta for `0.12.0` comes out (not yet). The thing is that I know it works with the `Ctrl` key, but I'm not certain if my code handles Mac's `Cmd` key too. It will still take time until `0.12.0` is ready for a beta test, as #37 still takes a long time. I just wanted to write this now so that I don't forget when the beta comes out.

**Comment by FelipeRearden** [comment]
> @FelipeRearden I'll need your help testing this when a beta for `0.12.0` comes out (not yet). The thing is that I know it works with the `Ctrl` key, but I'm not certain if my code handles Mac's `Cmd` key too. It will still take time until `0.12.0` is ready for a beta test, as #37 still takes a long time. I just wanted to write this now so that I don't forget when the beta comes out.

Sure @Taitava !!!!!!! 

You can count on me :) :) :)

Just one comment: If were easier for you we could make this hotkey only available with CRTL instead of CMD. Since MacOS does not have any OS hotkey applied to CRTL+1...9

Have a great day!!!!!

**Comment by Taitava** [comment]
> If were easier for you we could make this hotkey only available with CRTL instead of CMD. Since MacOS does not have any OS hotkey applied to CRTL+1...9

I don't even know how it goes now on macOS. `Ctrl`/`Cmd` + click on a button uses a bit different logic than the `Ctrl`/`Cmd` + `Shift` + number feature. So to be honest, even though I have written the key `Cmd` to the tooltips, I'm not sure if the code actually uses `Cmd` or `Ctrl` on macOS. But you can test later how it happens to be, and I can change it if it's wrong.

I'm not familiar with macOS, but I'm familiar with the trait in Obsidian forums, that every time when a hotkey involving `Ctrl` is mentioned, it's paired with `Cmd` on macOS (e.g. `Ctrl`/`Cmd` + `N`), not with macOS's `Ctrl`. So I'd like it to be `Cmd` on macOS, instead of `Ctrl`, just for the sake of consistency within the ecosystem of Obsidian.

Have a nice day, too! 🙂

**Comment by Taitava** [comment]
Done. Will be released in `0.12.0`. See a screenshot here: https://github.com/Taitava/obsidian-shellcommands/discussions/139#discussioncomment-2538342

**Comment by Taitava** [comment]
@FelipeRearden The beta is now available, so you can test the hotkeys whenever you have time 🙂:

> @FelipeRearden I'll need your help testing this when a beta for `0.12.0` comes out (not yet). The thing is that I know it works with the `Ctrl` key, but I'm not certain if my code handles Mac's `Cmd` key too. It will still take time until `0.12.0` is ready for a beta test, as #37 still takes a long time. I just wanted to write this now so that I don't forget when the beta comes out.

**Comment by Taitava** [comment]
Released.
