### ISSUE TITLE
[feature request] When using ask after execution, allow selection of output for inserting

### ISSUE THREAD

**Issue by pcause** [Taitava/obsidian-shellcommands#158]
When one selected "ask" for the output destination, a box is show displaying the output.  It would be great to allow a user to select which part of the output should be inserted/pasted/etc

**Comment by Taitava** [comment]
Hi, thank you for your suggestion! 🙂 

Yea, I think that when something is selected in the output textarea, the current _"Redirect:"_ could change to _"Redirect selection:"_. When nothing is selected, then the redirection would use all the text, just like now.

A workaround for now is to edit the output text by removing everything except the text that is wanted, but it's slower than just selecting text, so I do agree that this idea could be implemented. Should not even be a big thing to do.

Thanks! 🙂

**Comment by Taitava** [comment]
> I think that when something is selected in the output textarea, the current _"Redirect:"_ could change to _"Redirect selection:"_.

Actually, that text will not change, but I'll add just a tip text telling that if something is selected, then the selection will be used instead of the whole text.

**Comment by Taitava** [comment]
Done. Will be released in `0.11.0`.

**Comment by pcause** [comment]
Thanks.

**Comment by Taitava** [comment]
And it can be tested in a beta test: https://github.com/Taitava/obsidian-shellcommands/discussions/166
