### ISSUE TITLE
Settings: Widen the command fields

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#19]
![kuva](https://user-images.githubusercontent.com/13002142/133598829-4924c07b-6c2b-435f-8be8-0806c9234f82.png)

The above screenshot shows how small the command fields are. Take a look at the *Git Bash* command field. The  command is so long that it's not completely visible. And I suspect that users can have far more longer commands than I currently have. One shine of light is the gray preview text at the left side, that always shows the full command, but still the text field should be longer.

There is one issue to be dealt with when widening the text field. It can compete of space with the preview text. I need to find a way to extract the preview text on a new row. This way the preview text could go wider than it currently can, and the text field can be  widened too.

(See the last command preview in the screenshot. It shows that I happened to take the screenshot at time *13:37*, which becomes *1337*, which means *elite* in some old nerd slang 😄 ).

**Comment by FelipeRearden** [comment]
My suggestion about the UI - I'm gonna use `Git GUI` as an example:

[line1 - Command Name] -> Git GUI 
[line 2 - Command Preview] -> start git-gui
[line 3 - Command Field] -> [start git-gui] [icon]
[horizontal line]

I don't know if it is feasible but this way we get more space for `preview` and `field`

Another idea could be fix the [icon] in the right side in the [line 1] which will open space for [line 3]

**Comment by Taitava** [comment]
Yea, three rows is actually quite good idea! I'll play around and see which order will look best. Command preview at the middle and command field at the bottom might be a good idea. And moving the gear icon (+ delete icon like you said) to line 1 is good idea too.

**Comment by Taitava** [comment]
I think I'll swap command preview and command field lines so that the preview will be at the bottom. This is how it will approximately look like:

![kuva](https://user-images.githubusercontent.com/13002142/133726474-da47bf2f-1aef-4276-8d7f-c2a0d43ea643.png)

Note that this screenshot does not have the delete button as I'm developing it in a separate Git branch. But delete will be at the right side of the cog icon.

**Comment by Taitava** [comment]
Done.

**Comment by FelipeRearden** [comment]
@Taitava, it is much better swapping `line 2` and `line 3` !!!!!

The new beautiful UI is working perfect on MacOS - Release 0.3.0

**Comment by Taitava** [comment]
Thank you! Nice to know that it looks good. I'm not so graphical person that I could always be able to design clear user interfaces. I'm more technical person who makes stuff work behind the scenes, and then the outfit can sometimes be not so beautiful 😄 .

**Comment by FelipeRearden** [comment]
@Taitava , I think you a doing a fantastic job. 

Thanks for sharing. Now I know this I will me more comfortable to suggest anything related to the UI. 

:)

**Comment by Taitava** [comment]
Sure, all suggestions are welcome! Thanks! 🙂
