### ISSUE TITLE
Settings: Add a delete button next to each command field

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#20]
Currently commands are deleted by clearing their text field and then clicking an *APPLY DELETIONS* button. It's not the cleanest way. If each command would have their own delete button/icon, then the apply button can be removed to save space.

**Comment by Taitava** [comment]
Mostly done, but still need to remove/hide the setting field after the actual setting is deleted. I don't know yet how to do this.

**Comment by Taitava** [comment]
Done.

**Comment by FelipeRearden** [comment]
@Taitava, working perfect on MacOS!

Thank you so much for this :)

**Comment by Taitava** [comment]
Thanks! 🙂
