### ISSUE TITLE
about command not fount

### ISSUE THREAD

**Issue by cksspk** [Taitava/obsidian-shellcommands#215]
env: mac pro m1
<img width="620" alt="image" src="https://user-images.githubusercontent.com/37790595/167052265-91c48a9f-5f32-4ec0-a2fd-8725f032e842.png">

<img width="720" alt="image" src="https://user-images.githubusercontent.com/37790595/167052346-51bb2847-ba2a-4e19-b947-a17653ad793f.png">

<img width="342" alt="image" src="https://user-images.githubusercontent.com/37790595/167052367-07e910dd-1327-455d-a18e-bf43fc60ffe2.png">

**Comment by Taitava** [comment]
Hi,

it's actually already repoted here:
 - https://github.com/Taitava/obsidian-shellcommands/discussions/150
 - https://github.com/Taitava/obsidian-shellcommands/discussions/191
 - https://github.com/Taitava/obsidian-shellcommands/discussions/189

#204 will provide an easier solution to it (when it gets released in `0.13.0`), but before that you can use a workaround where you use a command `export PATH=$PATH:/Users/cksspk/soft/upgit/; upgit :clipboard -f markdown-simple` which combines adding a directory to `PATH` and executing the `upgit` command. The `~/.zshrc` profile file is not used when executing shell commands using this plugin, but I don't know why it's not used (I should mention this in the documentation).

Also, when reporting problems/ideas, please use [discussions](https://github.com/Taitava/obsidian-shellcommands/discussions) for it. In this repository, _issues_ are meant for something that is already decided how it's going to be implemented/fixed, and before that a planning phase is needed, which is done in _discussions_. Thank you! 🌞
