### ISSUE TITLE
Ability to show intermediate outputs

### ISSUE THREAD

**Issue by pulinagrawal** [Taitava/obsidian-shellcommands#259]
I am not sure if it is possible but it will be great if intermediate outputs can also be shown.

**Comment by Taitava** [comment]
Yea, it's discussed here: https://github.com/Taitava/obsidian-shellcommands/discussions/64 . Will probably take quite a lot of time.

**Comment by pulinagrawal** [comment]
@Taitava Thanks for quick response to that.

As a compromise can we have something like a notification when a command starts?

**Comment by Taitava** [comment]
Are you using events to execute shell commands? So you are not manually starting your commands?

I think some kind of ability to monitor executed shell command processes could be planned. A notification balloon could be one approach, yes. Thank you for the idea! 🙂 It could later be developed further to make it more advanced.

**Comment by pulinagrawal** [comment]
@Taitava  Sorry I missed this message.
I was using hotkeys to execute.

**Comment by Taitava** [comment]
No problem! 🙂
