### ISSUE TITLE
Text styling for output (ANSI code)

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#329]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/328

Will use the following library: https://github.com/drudru/ansi_up

- [x] Go through ansi_up's source code to check that it's legit.
- [x] Write documentation.

**Comment by Taitava** [comment]
Done otherwise, but documentation is not done yet.
- [ ] Write documentation.

**Comment by Taitava** [comment]
This is now released, but I still need to write documentation, so I'm keeping this issue open.

**Comment by OMSmolina** [comment]
In output: `Ask after execution` Ansi colors not working correctly.

![image](https://github.com/Taitava/obsidian-shellcommands/assets/6513086/3e1c5efe-1265-4c1b-b4af-c698b5786af1)

**Comment by Taitava** [comment]
> This is now released, but I still need to write documentation, so I'm keeping this issue open.

It's been over a year now, but I'll start writing the documentation finally now.

---

Just for the record, I have answered these two old messages in other discussions earlier, so I'll add links to them here.

> In output: `Ask after execution` Ansi colors not working correctly.

Discussed here: https://github.com/Taitava/obsidian-shellcommands/discussions/328#discussioncomment-8097880

> It would be nice to have an option to just remove ANSI code

Discussed here: https://github.com/Taitava/obsidian-shellcommands/discussions/328#discussioncomment-8264772

**Comment by Taitava** [comment]
Here's the documentation finally:
- ANSI code: https://publish.obsidian.md/shellcommands/Output+handling/Styling+for+output+text+with+ANSI+code
- Monospace formatting: https://publish.obsidian.md/shellcommands/Output+handling/Output+channel+-+Notification+balloon#Monospace+formatting

So, everything belonging to this issue is done now.
