### ISSUE TITLE
Get output text from shell commands, part 1

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#34]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/16

This issue is meant for implementing **part** of the features mentioned in the above discussion. This does not mean that other features would not be implemented later. This is just a way to split work into well managed parts.

Implement these *channels* for shell command output (stdout):
- [x] Ignore the output. Just like it's currently done. (Will be the default option).
- [x] A balloon on the top right corner. Suitable for multirow but short outputs, like a list of around five files in a folder.
- [x]  Insert into the current file at caret location. Can also replace text if something was selected at the time of executing a command.

**Comment by Taitava** [comment]
Still needed:
- [ ] Handle stderr
- [ ] Write documentation
- [ ] Test, test, test!

**Comment by Taitava** [comment]
Implemented & released in `0.5.0`.

**Comment by FelipeRearden** [comment]
Working perfect on:

Version `0.5.0`
MacOS 11.1
Obsidian 0.12.15
