### ISSUE TITLE
Confirmation before executing a shell command

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#35]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **Taitava** September 18, 2021</sup>
Some commands can be quite dangerous, especially if they involve deleting files, writing to files, or use unpredictable variables such as `{{selection}}` or `{{clipboard}}` ([there is no way to escape/encode variable values at the moment](https://github.com/Taitava/obsidian-shellcommands/issues/11)).

I'd like to add a simple toggle for each shell command. If the toggle is on, then every time the user tries to execute the shell command, they are prompted like this:

> ## Actual shell command here
> **Execute this shell command?**
> Alias: command alias here
> [Yes, execute] (no cancel button, user can click X to cancel, or click background or hit Esc)

**Comment by FelipeRearden** [comment]
Working perfect on:
Version `0.4.1`
MacOS 11.1
Obsidian 0.12.15

**Comment by FelipeRearden** [comment]
@Taitava 

The icon for showing that the Shell Command have `Ask Confirmation` is fantastic !!!!!!!!!!

**Comment by Taitava** [comment]
Nice! I like the general idea of having this kind of "special attention" icons to denote that there's something special going on that would otherwise require to open the modal in order to notice it. However, the iconset that Obsidian's API provides is quite limited, so I didn't have much options when choosing an icon.

I'm thinking about importing a larger icon library, such as [Feather icons](https://feathericons.com/), that [Customizable Sidebar](https://github.com/phibr0/obsidian-customizable-sidebar) uses. Then I will probably replace some of the current icons.

**Comment by FelipeRearden** [comment]
Hum ... a question (you will understand why after :) )

Do you see the same icons in your vault?
![Screen Shot 2021-10-02 at 10 17 53](https://user-images.githubusercontent.com/85180696/135718042-334582bd-b48f-4a58-a38f-d2f8b94ec9ce.png)

**Comment by Taitava** [comment]
> Hum ... a question (you will understand why after :) )

No, on Windows the icons are different: (and I'm using a light theme)
![kuva](https://user-images.githubusercontent.com/13002142/135718892-60700abc-0985-4c6f-a2df-593ce36810f8.png)

It's interesting to see how the icons look like on Mac.

**Comment by FelipeRearden** [comment]
Just as I expected :) 

I'm asking this because the best themes in Obsidian already uses it's own "icons data base". This way, the plugin creators/developers can choose to add (or not add) an icon library. 
- Thats why my icons are different :)
- If I use the Obsidian light theme on MacOS, we will have the same icons :)

**Comment by Taitava** [comment]
Aa, nice that you can swap icons with a plugin! 🙂

**Comment by FelipeRearden** [comment]
Yeah, Themes use this Icon Swapper plugin to "import" new icons :)
