### ISSUE TITLE
URIs Execute Twice

### ISSUE THREAD

**Issue by wallysaurus** [Taitava/obsidian-shellcommands#405]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/404

<div type='discussions-op-text'>

<sup>Originally posted by **wallysaurus** April 13, 2024</sup>
When pressing the execute button directly in the settings menu, I have no problem running the script once like it should, however, when I click on a URI link to execute the command, two instances get created.

https://github.com/Taitava/obsidian-shellcommands/assets/69739715/84687073-72b1-4822-ac74-47cae127f058

</div>

**Comment by Taitava** [comment]
Please don't create issues 🙂. My workflow is that first users create discussions, and if they lead to something actionable that needs code changes, then I'll create issues 🙂. Unfortunately I haven't found a setting in GitHub for limiting the ability to create issues for the repository's maintainer only.

I'll reopen this issue if we can find something to fix in the plugin. In the meantime, lets continue the discussion in #404 . 👍
