### ISSUE TITLE
Settings: Remember scroll position

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#71]
I do a lot of testing that requires me to open and close the settings panel a million times in a short time. I have a long list of commands and I usually need to go back to settings to edit a command I just created. As I'm tired of scrolling back to the correct command, I decided to make the settings panel remember the scroll position during a session.

The scroll position is not saved to the settings file, so scrolling starts from top again when Obsidian is restarted, but I guess that's actually expected.

**Comment by FelipeRearden** [comment]
1000% agree @Taitava !!!! would be great to have this nice feature! I feel this need too :)

> The scroll position is not saved to the settings file, so scrolling starts from top again when Obsidian is restarted, but I guess that's actually expected.

100% agree. Much better this way! We just need to remember on each Obsidian "section"

Have a great day!!!
