### ISSUE TITLE
Clipboard output channel: Make notification balloon optional

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#75]
Discussed in #16 . Direct links to comments discussing this:
 - https://github.com/Taitava/obsidian-shellcommands/discussions/16#discussioncomment-1469759
 - https://github.com/Taitava/obsidian-shellcommands/discussions/16#discussioncomment-1474523

**Comment by Taitava** [comment]
Done. Default setting: notification is on, and the notification message shows a tip that the notification can be turned off in settings.

**Comment by FelipeRearden** [comment]
> Done. Default setting: notification is on, and the notification message shows a tip that the notification can be turned off in settings.

Thank you very much @Taitava :)

**Comment by FelipeRearden** [comment]
Working perfect on version `0.7.0 beta4` Obsidian `0.12.19` on MacOS `11.6`

Thank you @Taitava !!!!!!

**Comment by Taitava** [comment]
Oh, good! I had already forgotten this is not yet released - it was done so long ago. 😆

But good that `0.7.0` is finally so close 🙂.

**Comment by Taitava** [comment]
Done & released.
