### ISSUE TITLE
A new variable {{note_content}}

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#77]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/57

Gets the current note's content without YAML frontmatter.

**Comment by Taitava** [comment]
My question in the forum has been answered: https://forum.obsidian.md/t/how-to-get-current-file-content-without-yaml-frontmatter/26197/2

I haven't tried the solution yet.

**Comment by FelipeRearden** [comment]
> My question in the forum has been answered: https://forum.obsidian.md/t/how-to-get-current-file-content-without-yaml-frontmatter/26197/2
> 
> 
> 
> I haven't tried the solution yet.

Great to know @Taitava ! Let's hope that we have a good solution 🙏

**Comment by marvinwu** [comment]
Thanks for this great plugin and it is very useful, just a very hacky thought , instead of using obsidian api, since we know the current file path already, can we just cat the file in bash to get the content ?

**Comment by Taitava** [comment]
> 

Thank you @marvinwu for your positive feedback! ❤️ `cat` works very well as a workaround solution, if users use it in their own shell commands. It just doesn't make it easy to get the content _without_ YAML frontmatter, in case a user doesn't want the frontmatter.

What comes to this actual `{{note_content}}` variable, in theory it could be implemented so that it would execute a `cat` command under the hood (I don't know if you meant to suggest that or not), but there's two reasons why I wouldn't do it:
- I have a design principle in my head that the plugin should only execute shell commands a user has defined themselves. If there would be any "under the hood" shell commands, the plugin should at least show the shell command to the user and ask a permission to execute it.
- It's not actually hard to use the Obsidian API to retrieve the file content. It just takes some time to refactor the current variable system to support asynchronous processing (using `Promise`s). Now that this issue is almost a year old, I have become better at using `Promise`s during these months, so the problem should not be so big anymore.

But anyway, `cat` is a good workaround for users until this variable finally gets implemented.

**Comment by Taitava** [comment]
## Success
I was able to make this variable work! I did the needed variable system refactoring (issue #265). I still need to do extensive testing, because the changes were quite big, so need to ensure I didn't break anything in the variable parsing process.

I'll update this issue when the variable is ready to be released.

**Comment by Taitava** [comment]
Released now.
