### ISSUE TITLE
Settings: Split main settings view to tabs

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#85]
Currently, the main settings view contains the following settings:
- _Working directory_
- Shell commands
- _Error message duration_
- _Notification message duration_
- _Preview variables in command palette_
- A list of available variables (not actually settings, as there's nothing to configure).

#76 will bring more settings to the main view:
- _Macintosh default shell_
- _Linux default shell_
- _Windows default shell_

These settings will be divided into different tabs.

- [x] **Shell commands**
  - The list of shell commands.
  - The list of variables.
  - _Preview variables in command palette_ (until I come up with a better placement for this)

- [x] **Operating systems & shells**
  - _Working directory_
  - _Macintosh default shell_
  - _Linux default shell_
  - _Windows default shell_

- [x] **Output**
  - _Error message duration_
  - _Notification message duration_

**Shell commands** tab will be active by default, and it's the tab that a user will probably use more actively than the other tabs.

**Comment by Taitava** [comment]
This is how the main settings view looks after splitting to tabs:
![kuva](https://user-images.githubusercontent.com/13002142/139520441-0c6f2828-e985-4f65-8422-df1a8fc32584.png)

(Icons will change to something else in the future, but that's a topic for another discussion.)

**Comment by FelipeRearden** [comment]
What a great new window @Taitava ! 👀 👀 👀 👀 👀 👀 👀

**Comment by Taitava** [comment]
Done & released.
